Soccer/Controllers/PlayersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Soccer.BLL.DTO;
using Soccer.BLL.Interfaces;
using Soccer.BLL.Infrastructure;

namespace Soccer.Controllers
{
    public class PlayersController : Controller
    {
        private readonly IPlayerService playerService;
        private readonly ITeamService teamService;
        public PlayersController(IPlayerService playerserv, ITeamService teamserv)
        {
            playerService = playerserv;
            teamService = teamserv;
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            return View(await playerService.GetPlayers());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                PlayerDTO player = await playerService.GetPlayer((int)id);
                return View(player);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }

        // GET: Players/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.ListTeams = new SelectList(await teamService.GetTeams(), "Id", "Name");
            return View();
        }

        // POST: Players/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PlayerDTO player)
        {
            if (ModelState.IsValid)
            {
                await playerService.CreatePlayer(player);
                return View("~/Views/Players/Index.cshtml", await playerService.GetPlayers());
            }
            ViewBag.ListTeams = new SelectList(await teamService.GetTeams(), "Id", "Name", player.TeamId);
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                PlayerDTO player = await playerService.GetPlayer((int)id);
                ViewBag.ListTeams = new SelectList(await teamService.GetTeams(), "Id", "Name", player.TeamId);
                return View(player);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }


        // POST: Players/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PlayerDTO player)
        {
            if (ModelState.IsValid)
            {
                await playerService.UpdatePlayer(player);
                return View("~/Views/Players/Index.cshtml", await playerService.GetPlayers());
            }
            ViewBag.ListTeams = new SelectList(await teamService.GetTeams(), "Id", "Name", player.TeamId);
            return View(player);
        }


        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                PlayerDTO player = await playerService.GetPlayer((int)id);
                return View(player);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await playerService.DeletePlayer(id);
            return View("~/Views/Players/Index.cshtml", await playerService.GetPlayers());
        }

    }
}

Soccer/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Mvc;
using Soccer.BLL.DTO;
using Soccer.BLL.Interfaces;
using Soccer.BLL.Infrastructure;

namespace Soccer.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ITeamService teamService;

        public TeamsController(ITeamService serv)
        {
            teamService = serv;
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            return View(await teamService.GetTeams());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                TeamDTO team = await teamService.GetTeam((int)id);
                return View(team);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }

        //
        // GET: /Teams/Create

        public IActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeamDTO team)
        {
            if (ModelState.IsValid)
            {
                await teamService.CreateTeam(team);
                return View("~/Views/Teams/Index.cshtml", await teamService.GetTeams());
            }
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                TeamDTO team = await teamService.GetTeam((int)id);
                return View(team);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }

        // POST: Teams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TeamDTO team)
        {
            if (ModelState.IsValid)
            {
                await teamService.UpdateTeam(team);
                return View("~/Views/Teams/Index.cshtml", await teamService.GetTeams());
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                TeamDTO team = await teamService.GetTeam((int)id);
                return View(team);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await teamService.DeleteTeam(id);
            return View("~/Views/Teams/Index.cshtml", await teamService.GetTeams());
        }

    }
}

Soccer/Views/Players/Create.cshtml
@model Soccer.BLL.DTO.PlayerDTO

@{
    ViewBag.Title = "Create";
}g

<h2>Add a new Player</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.Label("Player:")
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.Label("Age:")
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.Label("Position:")
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.Label("Club:")
                <select asp-for="TeamId" class="form-control" asp-items="ViewBag.ListTeams as SelectList"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List of Players</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Soccer/Views/Players/Delete.cshtml
@model Soccer.BLL.DTO.PlayerDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Player</h2>

<h3>Do you want to delete the Player?</h3>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
             @Html.Label("Player:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.Label("Age:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.Label("Position:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.Label("Club:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List of Players</a>
    </form>
</div>

Soccer/Views/Players/Details.cshtml
@model Soccer.BLL.DTO.PlayerDTO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.Label("Player:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.Label("Age:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.Label("Position:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.Label("Club:")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List of Players</a>
</p>

Soccer/Views/Players/Edit.cshtml
@model Soccer.BLL.DTO.PlayerDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit player</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                @Html.Label("Player:")
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.Label("Age:")
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.Label("Position:")
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.Label("Club:")
                <select asp-for="TeamId" class="form-control" asp-items="ViewBag.ListTeams as SelectList"></select>
                <span asp-validation-for="TeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Change" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back To List of Players", "Index")
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Soccer/Views/Players/Index.cshtml
@model IEnumerable<Soccer.BLL.DTO.PlayerDTO>

@{
    ViewBag.Title = "Index";
}

<h2>List of players</h2>

<p>
    <a asp-action="Create">Add new player</a>
</p>
<table class="table-condensed" style="width:100%">
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Position</th>
        <th>Club</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Team)
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
    </tr>
}
</table>

Soccer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Soccer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Clubs</a>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASP.NET Core Application
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>